version: '3.9'
services:
  nginx:
    container_name: ${APP_NAME}_nginx
    image: nginx
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
  frontend:
    container_name: ${APP_NAME}_frontend
    ports:
      - "3000:3000"
    build:
      context: ./docker/nextjs
    command: yarn dev
    tty: true
    stdin_open: true
    volumes:
      - ./src/frontend:/app
  backend:
    container_name: ${APP_NAME}_backend
    build: 
      context: ./docker/laravel
    # command: npm run dev
    ports:
      - "8000:8000"
      - "5173:5173"
    volumes:
      - ./src/backend:/var/www/html/app
    depends_on:
      - db
  db:
    container_name: ${APP_NAME}_db
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
      args:
        - MYSQL_DATABASE=${DB_NAME}
        - MYSQL_USER=${DB_USER}
        - MYSQL_PASSWORD=${DB_PASS}
        - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
    ports:
      - 3336:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
volumes:
  db-store: